quarkus.http.enable-compression=true
quarkus.log.category.MCP.level=DEBUG
quarkus.langchain4j.timeout=60s
quarkus.langchain4j.openai.log-requests=true
quarkus.langchain4j.openai.log-responses=true

quarkus.langchain4j.mcp.DEMO.transport-type=streamable-http
quarkus.langchain4j.mcp.DEMO.url=http://localhost:8080/mcp

quarkus.langchain4j.mcp.JFX.transport-type=stdio
quarkus.langchain4j.mcp.JFX.command=jbang,jfx@quarkiverse/quarkus-mcp-servers
quarkus.langchain4j.mcp.JFX.log-requests=true
quarkus.langchain4j.mcp.JFX.log-responses=true
quarkus.langchain4j.mcp.JFX.environment.TAVILY_API_KEY=your_api_key_here

quarkus.langchain4j.openai.api-key=xxx

quarkus.langchain4j.mcp.registry-client.REGISTRY.log-requests=true
quarkus.langchain4j.mcp.registry-client.REGISTRY.log-responses=true
quarkus.mcp.server.support-langchain4j-annotations=false